# Generated by Django 5.1.3 on 2026-09-17 08:16

from django.db import migrations, models


def link_existing_departments(apps, schema_editor):
    """Existing circulars get the departments their candidates were uploaded under."""
    Candidate = apps.get_model("recruitment", "Candidate")
    Through = apps.get_model("recruitment", "Circular").departments.through
    pairs = set(Candidate.objects.values_list("circular_id", "department_id"))
    Through.objects.bulk_create(
        [Through(circular_id=c, department_id=d) for c, d in pairs], ignore_conflicts=True
    )


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='circular',
            name='departments',
            field=models.ManyToManyField(blank=True, help_text='Departments this circular is hiring for.', related_name='circulars', to='recruitment.department'),
        ),
        migrations.RunPython(link_existing_departments, migrations.RunPython.noop),
    ]
