# Generated by Django 5.1.3 on 2026-09-17 09:12

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_circular_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='body_language_mark',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Out of 5. Leave empty if not taken.', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('5'))], verbose_name='Body language'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='dress_up_mark',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Out of 5. Leave empty if not taken.', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('5'))], verbose_name='Dress up'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='candidate',
            name='marks_out_of',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='candidate',
            name='score_percent',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='source',
            field=models.CharField(choices=[('admin', 'Added by HR'), ('upload', 'File upload'), ('online', 'Online registration')], default='admin', max_length=10),
        ),
        migrations.AddField(
            model_name='candidate',
            name='total_marks',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='viva_mark',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Out of 5. Leave empty if not taken.', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('5'))], verbose_name='Viva'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='written_mark',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Out of 5. Leave empty if not taken.', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('5'))], verbose_name='Written'),
        ),
        migrations.AddField(
            model_name='circular',
            name='registration_open',
            field=models.BooleanField(default=True, help_text='Candidates can register online for this circular (only if it is also active).'),
        ),
    ]
