# Generated by Django 5.1.3 on 2026-09-17 09:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_marks_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='available_date',
            field=models.DateField(blank=True, help_text='Date the candidate can join.', null=True, verbose_name='Available date'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='expected_salary',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Expected salary (BDT)'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1 to 5 stars.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
