# Generated by Django 5.1.3 on 2026-09-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_candidate_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='circular',
            name='interview_at',
            field=models.DateTimeField(blank=True, help_text='Shown to candidates after registration and on the result page.', null=True, verbose_name='Interview date & time'),
        ),
    ]
