# Generated by Django 5.1.3 on 2026-09-19 04:30

import django.core.validators
import recruitment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0006_circular_interview_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='cv',
            field=models.FileField(blank=True, help_text='PDF, DOC or DOCX - maximum 1 MB.', upload_to=recruitment.models.cv_upload_to, validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx']), recruitment.models.validate_cv_size], verbose_name='CV'),
        ),
    ]
