# Generated by Django 5.1.3 on 2026-09-20 06:35

import django.core.validators
import django.db.models.deletion
import recruitment.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0007_candidate_cv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('instructions', models.TextField(blank=True, help_text='Shown to the candidate before the questions start.')),
                ('token', models.CharField(default=recruitment.models.new_exam_token, editable=False, max_length=32, unique=True)),
                ('duration_minutes', models.PositiveSmallIntegerField(blank=True, help_text='The timer starts when the candidate enters their phone number, and the sheet closes itself when the time is up. Leave empty for no time limit.', null=True, verbose_name='Time limit (minutes)')),
                ('questions_per_candidate', models.PositiveSmallIntegerField(blank=True, help_text='Each candidate gets this many questions, picked at random from the list. Empty = all questions.', null=True, verbose_name='Questions per candidate')),
                ('shuffle_questions', models.BooleanField(default=True, help_text='Every candidate sees the questions in a different order.', verbose_name='Shuffle question order')),
                ('shuffle_choices', models.BooleanField(default=True, help_text='Multiple choice options are shown in a different order.', verbose_name='Shuffle options')),
                ('is_open', models.BooleanField(default=True, help_text='Candidates can only answer while it is open.', verbose_name='Exam open')),
                ('show_score', models.BooleanField(default=False, help_text='Only the auto-marked part is shown.', verbose_name='Show score to candidate')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('circular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='recruitment.circular')),
                ('departments', models.ManyToManyField(blank=True, help_text='Leave empty to allow every department of the circular.', related_name='exams', to='recruitment.department')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('auto_score', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=6, null=True)),
                ('manual_score', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=6, null=True)),
                ('total_score', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=6, null=True)),
                ('out_of', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=6)),
                ('question_order', models.JSONField(default=list, editable=False)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to='recruitment.candidate')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='recruitment.exam')),
            ],
            options={
                'ordering': ['-submitted_at', '-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('text', models.TextField(verbose_name='Question')),
                ('kind', models.CharField(choices=[('mcq', 'Multiple choice'), ('text', 'Written answer')], default='mcq', max_length=10, verbose_name='Answer type')),
                ('marks', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.25'))])),
                ('required', models.BooleanField(default=True, help_text='The candidate must answer this question.')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='recruitment.exam')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('text', models.CharField(max_length=300)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='recruitment.question')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(blank=True, max_length=300)),
                ('text_answer', models.TextField(blank=True)),
                ('awarded', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recruitment.choice')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='recruitment.examattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='recruitment.question')),
            ],
            options={
                'ordering': ['question__order', 'question_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='examattempt',
            constraint=models.UniqueConstraint(fields=('exam', 'candidate'), name='unique_attempt_per_candidate'),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='unique_answer_per_question'),
        ),
    ]
