# Generated by Django 5.1.3 on 2026-09-21 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0008_written_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='strict_mode',
            field=models.BooleanField(default=True, help_text='Needs a time limit. The sheet is submitted at once if the candidate switches tab, minimises, opens another window or presses Print Screen. Copy, paste and right-click are blocked. Answers are saved automatically; the candidate submits, or the sheet is handed in when time is over.', verbose_name='Strict mode (anti-cheating)'),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='draft',
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='events',
            field=models.JSONField(default=list, editable=False),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='submit_reason',
            field=models.CharField(blank=True, choices=[('submitted', 'Submitted by candidate'), ('time_up', 'Time over'), ('tab_switch', 'Left the exam page'), ('window_blur', 'Opened another window'), ('screenshot', 'Screenshot key pressed'), ('page_closed', 'Closed the page')], editable=False, max_length=20),
        ),
    ]
