# Generated by Django 5.1.3 on 2026-09-21 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0009_exam_strict_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='waiting_reason',
            field=models.TextField(blank=True, help_text='Why this candidate is on the waiting list. Never shown to the candidate.', verbose_name='Waiting reason (HR only)'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('selected', 'Selected'), ('waiting', 'Waiting'), ('not_selected', 'Not Selected')], db_index=True, default='pending', max_length=20),
        ),
    ]
