# Generated by Django 5.1.3 on 2026-09-21 09:19

import django.core.validators
import django.db.models.deletion
import recruitment.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0010_waiting_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('max_marks', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('1'))])),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive criteria are not on new marking sheets.')),
            ],
            options={
                'verbose_name_plural': 'evaluation criteria',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InterviewSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_combined', models.BooleanField(default=True, verbose_name='Show a combined final result')),
                ('written_weight', models.PositiveSmallIntegerField(default=40, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Written exam weight (%)')),
                ('interview_weight', models.PositiveSmallIntegerField(default=60, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Interview weight (%)')),
            ],
        ),
        migrations.CreateModel(
            name='SmsGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='IGL SMS', max_length=100)),
                ('base_url', models.URLField(default='http://sms.iglweb.com/api/v1/send', verbose_name='API URL')),
                ('api_key', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='candidate',
            name='education',
            field=models.TextField(blank=True, help_text='Degrees / institutions.'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='experience',
            field=models.TextField(blank=True, help_text='Work experience summary.'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='interview_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Interview Scheduled'), ('started', 'Interview Started'), ('completed', 'Interview Completed'), ('evaluation_pending', 'Evaluation Pending'), ('evaluation_completed', 'Evaluation Completed'), ('selected', 'Selected'), ('rejected', 'Rejected'), ('on_hold', 'On Hold')], db_index=True, default='pending', max_length=24),
        ),
        migrations.AddField(
            model_name='exam',
            name='pass_percent',
            field=models.PositiveSmallIntegerField(default=40, help_text='The written result shows Passed / Failed against this percentage.', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Pass mark (%)'),
        ),
        migrations.CreateModel(
            name='InterviewCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('interview_date', models.DateField()),
                ('interview_time', models.TimeField()),
                ('venue', models.CharField(max_length=255)),
                ('information', models.TextField(blank=True, verbose_name='Interview information')),
                ('message_template', models.TextField(default='Dear {candidate_name},\nYou are invited for an interview for the {department} department.\nDate: {interview_date}\nTime: {interview_time}\nVenue: {venue}\n\nIGL Group', verbose_name='SMS message')),
                ('uploaded_file', models.FileField(upload_to=recruitment.models.interview_call_upload_to)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('headers', models.JSONField(default=list, editable=False)),
                ('column_map', models.JSONField(default=dict, editable=False)),
                ('stage', models.CharField(choices=[('mapping', 'Map columns'), ('ready', 'Ready')], default='mapping', max_length=10)),
                ('total_rows', models.PositiveIntegerField(default=0, editable=False)),
                ('duplicate_rows', models.PositiveIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interview_calls', to='recruitment.department')),
                ('gateway', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='recruitment.smsgateway')),
            ],
            options={
                'ordering': ['-interview_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewCallCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField(default=0)),
                ('candidate_name', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, help_text='Cleaned 01XXXXXXXXX - one per candidate.', max_length=20)),
                ('phone_raw', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(blank=True, max_length=254)),
                ('candidate_ref', models.CharField(blank=True, max_length=100, verbose_name='Candidate ID')),
                ('department_text', models.CharField(blank=True, max_length=200)),
                ('additional_data', models.JSONField(blank=True, default=dict)),
                ('is_valid', models.BooleanField(default=True)),
                ('error', models.CharField(blank=True, max_length=255)),
                ('sms_status', models.CharField(choices=[('not_sent', 'Not sent'), ('queued', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('invalid', 'No valid phone')], db_index=True, default='not_sent', max_length=10)),
                ('sms_response', models.TextField(blank=True)),
                ('sms_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interview_call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='recruitment.interviewcall')),
                ('matched_candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_calls', to='recruitment.candidate')),
            ],
            options={
                'ordering': ['row_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InterviewerDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviewer_links', to='recruitment.department')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('designation', models.CharField(blank=True, max_length=120)),
                ('can_edit_written_marks', models.BooleanField(default=False, help_text='Allow this interviewer to mark / change written exam answers.', verbose_name='May mark written answers')),
                ('can_edit_submitted', models.BooleanField(default=False, help_text='Allow changes to an evaluation after it was submitted (until the Admin makes the final decision).', verbose_name='May edit after submitting')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('departments', models.ManyToManyField(blank=True, related_name='interviewers', through='recruitment.InterviewerDepartment', to='recruitment.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interviewer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__first_name', 'user__email'],
            },
        ),
        migrations.AddField(
            model_name='interviewerdepartment',
            name='interviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_links', to='recruitment.interviewerprofile'),
        ),
        migrations.CreateModel(
            name='InterviewEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_mark', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=6)),
                ('out_of', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=6)),
                ('comments', models.TextField(blank=True)),
                ('strengths', models.TextField(blank=True)),
                ('weaknesses', models.TextField(blank=True)),
                ('recommendation', models.CharField(blank=True, choices=[('strongly_recommend', 'Strongly recommend'), ('recommend', 'Recommend'), ('neutral', 'Neutral'), ('not_recommend', 'Not recommended')], max_length=24)),
                ('remarks', models.TextField(blank=True, verbose_name='Remarks')),
                ('is_submitted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='recruitment.candidate')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='recruitment.department')),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['candidate', 'interviewer__first_name'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterion_name', models.CharField(max_length=120)),
                ('max_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mark', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('criterion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recruitment.evaluationcriterion')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='recruitment.interviewevaluation')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SmsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('sender_id', models.CharField(max_length=30)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped (already sent)')], db_index=True, default='pending', max_length=10)),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('api_response', models.TextField(blank=True)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('is_retry', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('interview_call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_logs', to='recruitment.interviewcall')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_logs', to='recruitment.interviewcallcandidate')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SmsSenderId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.CharField(max_length=30, verbose_name='Approved Sender ID')),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_ids', to='recruitment.smsgateway')),
            ],
            options={
                'ordering': ['-is_default', 'sender_id'],
            },
        ),
        migrations.AddField(
            model_name='interviewcall',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='recruitment.smssenderid'),
        ),
        migrations.AddConstraint(
            model_name='interviewcallcandidate',
            constraint=models.UniqueConstraint(condition=models.Q(('phone', ''), _negated=True), fields=('interview_call', 'phone'), name='unique_phone_per_call'),
        ),
        migrations.AddConstraint(
            model_name='interviewerdepartment',
            constraint=models.UniqueConstraint(fields=('interviewer', 'department'), name='unique_interviewer_department'),
        ),
        migrations.AddConstraint(
            model_name='interviewevaluation',
            constraint=models.UniqueConstraint(fields=('candidate', 'interviewer'), name='unique_evaluation_per_interviewer'),
        ),
        migrations.AddConstraint(
            model_name='evaluationscore',
            constraint=models.UniqueConstraint(fields=('evaluation', 'criterion'), name='unique_score_per_criterion'),
        ),
        migrations.AddConstraint(
            model_name='smssenderid',
            constraint=models.UniqueConstraint(fields=('gateway', 'sender_id'), name='unique_sender_per_gateway'),
        ),
    ]
