# Generated by Django 5.1.3 on 2026-09-21 09:40

import re

from django.db import migrations, models


def mark_445000_as_sent(apps, schema_editor):
    """SMS the API accepted (reply code 445000) were logged as failed - correct them so Retry never resends."""
    SmsLog = apps.get_model("recruitment", "SmsLog")
    Person = apps.get_model("recruitment", "InterviewCallCandidate")
    Candidate = apps.get_model("recruitment", "Candidate")
    accepted = re.compile(r"(?<!\d)445000(?!\d)")
    for log in SmsLog.objects.filter(status="failed"):
        if not accepted.search(log.api_response or "") or not (200 <= (log.http_status or 200) < 300):
            continue
        log.status = "success"
        log.error = ""
        log.save(update_fields=["status", "error"])
        person = Person.objects.filter(pk=log.recipient_id).first()
        if person is not None and person.sms_status != "sent":
            person.sms_status = "sent"
            person.sms_sent_at = person.sms_sent_at or log.sent_at
            person.save(update_fields=["sms_status", "sms_sent_at"])
            # interview_status was removed in 0017 (one main status) - only touch it while it exists
            if person.matched_candidate_id and any(f.name == "interview_status" for f in Candidate._meta.get_fields()):
                Candidate.objects.filter(pk=person.matched_candidate_id, interview_status="pending").update(
                    interview_status="scheduled"
                )


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0012_default_evaluation_criteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsgateway',
            name='success_codes',
            field=models.CharField(default='445000', help_text='Codes in the API reply that mean the SMS was accepted, comma separated (IGL SMS: 445000).', max_length=200, verbose_name='Success codes'),
        ),
        migrations.RunPython(mark_445000_as_sent, migrations.RunPython.noop),
    ]
