# Generated by Django 5.1.3 on 2026-09-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0013_sms_success_codes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interviewcall',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='interviewcall',
            name='interview_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interviewcall',
            name='interview_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interviewcall',
            name='message_template',
            field=models.TextField(default='Dear {candidate_name},\nYou are invited for an interview at IGL Group.\n\nIGL Group', verbose_name='SMS message'),
        ),
        migrations.AlterField(
            model_name='interviewcall',
            name='venue',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
