# Generated by Django 5.1.3 on 2026-09-22 04:32

import django.core.validators
from decimal import ROUND_HALF_UP, Decimal

from django.db import migrations, models

FIVE = Decimal("5")


def whole(value):
    return int(Decimal(value).quantize(Decimal("1"), rounding=ROUND_HALF_UP))


def to_whole_marks(apps, schema_editor):
    """
    Before the columns become whole numbers:
      - every criterion becomes "out of 5"; existing scores are rescaled (e.g. 20/25 -> 4/5) and rounded
      - .5 marks are rounded half up (3.5 -> 4) - on the interview sheet's Written mark too
      - totals are recalculated from the new marks
    """
    Criterion = apps.get_model("recruitment", "EvaluationCriterion")
    Score = apps.get_model("recruitment", "EvaluationScore")
    Evaluation = apps.get_model("recruitment", "InterviewEvaluation")
    Candidate = apps.get_model("recruitment", "Candidate")

    Criterion.objects.all().update(max_marks=FIVE)
    for score in Score.objects.all():
        old_max = Decimal(score.max_marks or FIVE) or FIVE
        if score.mark is not None:
            mark = whole(Decimal(score.mark) * FIVE / old_max)
            score.mark = min(max(mark, 0), 5)
        score.max_marks = FIVE
        score.save(update_fields=["mark", "max_marks"])
    for evaluation in Evaluation.objects.all():
        scores = list(Score.objects.filter(evaluation=evaluation))
        evaluation.total_mark = sum((Decimal(s.mark) for s in scores if s.mark is not None), Decimal("0"))
        evaluation.out_of = FIVE * len(scores)
        evaluation.save(update_fields=["total_mark", "out_of"])
    for c in Candidate.objects.exclude(written_mark=None):
        mark = min(max(whole(c.written_mark), 0), 5)
        Candidate.objects.filter(pk=c.pk).update(
            written_mark=mark, total_marks=mark, marks_out_of=5,
            score_percent=(Decimal(mark) * 100 / FIVE).quantize(Decimal("0.01")),
        )


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0016_move_old_marks_to_criteria'),
    ]

    operations = [
        migrations.RunPython(to_whole_marks, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='candidate',
            name='interview_status',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='written_mark',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Whole number 0 to 5. Leave empty if not taken.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Written'),
        ),
        migrations.AlterField(
            model_name='evaluationcriterion',
            name='max_marks',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='evaluationscore',
            name='mark',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='evaluationscore',
            name='max_marks',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
