# Generated by Django 5.2.17 on 2026-10-01 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0017_one_status_whole_marks'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('organisation', models.CharField(blank=True, max_length=160, verbose_name='Company / University / Institute')),
                ('designation', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='recruitment.candidate')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
