# Generated by Django 5.2.17 on 2026-10-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0018_candidate_references'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatereference',
            name='organisation',
            field=models.CharField(blank=True, max_length=160, verbose_name='Company / University'),
        ),
    ]
